[package]
name = "sp-common"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.12"
reqwest = "0.12.15"
object = "0.36.7"
semver = "1.0.26"
serde_json = "1.0.140"
dirs = "6.0.0"
tracing = "0.1.41"
serde = "1.0.219"
humantime = "2.2.0"
bitflags = "2.9.0"