name: Build & Publish Release Asset

on:
  release:
    types: [published]

jobs:
  build-and-upload:
    runs-on: macos-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Rust (stable)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build release binary
        run: cargo build --release

      - name: Upload binary to GitHub Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: target/release/sapphire
          asset_name: sapphire-${{ github.event.release.tag_name }}-macos-arm64
          asset_content_type: application/octet-stream
