name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  rust-macos-arm64:
    # Use the new M1 macOS 14 (Sonoma) runner, which is arm64-native 
    runs-on: macos-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Rust toolchain (Nightly)
        # macOS runners don’t come with Rust pre‑installed, so you need this 
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly # Keep nightly as per previous step
          override: true
          components: clippy, rustfmt 

      - name: Cache cargo registry & build artifacts
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          # Include toolchain in cache key
          key: ${{ runner.os }}-cargo-nightly-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-nightly-
            ${{ runner.os }}-cargo-

      - name: Verify runner architecture
        run: |
          echo "UNAME reports: $(uname -m)"

      - name: Check formatting (using Nightly rustfmt)
        run: cargo fmt -- --check

      - name: Run linters
        run: cargo clippy -- -D warnings

      - name: Check for outdated dependencies
        run: cargo outdated --exit-code 1

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
