name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  rust-macos-arm64:
    runs-on: macos-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        # macOS runners don’t come with Rust pre‑installed, so you need this 
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy, rustfmt

      - name: Cache cargo registry & build artifacts
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Verify runner architecture
        run: |
          echo "UNAME reports: $(uname -m)"

      # --- Added Steps ---
      - name: Check formatting
        run: cargo fmt -- --check

      - name: Run linters
        run: cargo clippy -- -D warnings
      # --- End Added Steps ---

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
